export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST"
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS"
export const FETCH_ADMIN_FAIL = "FETCH_ADMIN_FAIL"

export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST"
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS"
export const FETCH_EMPLOYEE_FAIL = "FETCH_EMPLOYEE_FAIL"

export const FETCH_WORKLOG_REQUEST = "FETCH_WORKLOG_REQUEST"
export const FETCH_WORKLOG_SUCCESS = "FETCH_WORKLOG_SUCCESS"
export const FETCH_WORKLOG_FAIL = "FETCH_WORKLOG_FAIL"
